- name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
  copy:
    content: hello world\n
    dest: /home/tcruz/testfile.txt

- name: Print Env Var
  debug:
    msg: "{{ lookup('env','test')}}"
